name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: I1
      id: i1
      uses: education/autograding-io-grader@v1
      with:
        test-name: I1
        command: g++ -std=c++11 main.cpp && ./a.out
        input: '5'
        expected-output: "[\\w,\\W]*A[\\s]*[\\r,\\n]+[\\w,\\W]*A[\\w,\\W]*B[\\s]*[\\r,\\n]+[\\w,\\W]*A[\\w,\\W]*B[\\w,\\W]*C[\\s]*[\\r,\\n]+[[\\w,\\W]*A[\\w,\\W]*B[\\w,\\W]*C[\\w,\\W]*D[\\s]*[\\r,\\n]+[\\w,\\W]*A[\\w,\\W]*B[\\w,\\W]*[\\w,\\W]*C[\\w,\\W]*D[\\w,\\W]*E[\\w,\\W]*"
        comparison-method: regex
        timeout: 10
        max-score: 10
    - name: I2
      id: i2
      uses: education/autograding-io-grader@v1
      with:
        test-name: I2
        command: g++ -std=c++11 main.cpp && ./a.out
        input: '3'
        expected-output: "[\\w,\\W]*A[\\s]*[\\r,\\n]+[\\w,\\W]*A[\\w,\\W]*B[\\s]*[\\r,\\n]+[\\w,\\W]*A[\\w,\\W]*B[\\w,\\W]*C[\\s]*"
        comparison-method: regex
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        I1_RESULTS: "${{steps.i1.outputs.result}}"
        I2_RESULTS: "${{steps.i2.outputs.result}}"
      with:
        runners: i1,i2
